# Generated by Django 6.0.4 on 2026-05-20 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='parent_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='billing.bill'),
        ),
    ]
