# Generated by Django 6.0.4 on 2026-05-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_prescriptionitem_bill_id_prescriptionitem_billed_on'),
        ('billing', '0003_bill_is_addon_bill_parent_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='appointment.visit'),
        ),
    ]
