# Generated by Django 6.0.4 on 2026-04-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='upadted_at',
            new_name='updated_at',
        ),
    ]
