# Generated by Django 6.0.4 on 2026-04-30 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medicine',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicinevariant'),
        ),
    ]
