# Generated by Django 6.0.4 on 2026-05-05 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_familymember_bld_grop_familymember_dob_and_more'),
        ('appointment', '0001_initial'),
        ('medicine', '0003_purchase_vendor_purchaseitem_purchase_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medicine',
        ),
        migrations.AddField(
            model_name='appointment',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.familymember'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicinevariant'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='should_deduct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='was_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
