# Generated by Django 6.0.4 on 2026-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_prescriptionitem_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
