# Generated by Django 6.0.4 on 2026-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_prescription_is_stock_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='was_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
