# Generated by Django 6.0.4 on 2026-05-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_booked_by_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
    ]
