# Generated by Django 6.0.4 on 2026-05-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_prescriptionitem_was_deducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='should_deduct',
            field=models.BooleanField(default=True),
        ),
    ]
