# Generated by Django 6.0.4 on 2026-05-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_prescriptionitem_should_deduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
