# Generated by Django 6.0.4 on 2026-05-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_add_appointment_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='bill_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='billed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
