# Generated by Django 6.0.4 on 2026-04-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_prescription_prescriptionitem_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
