# Generated by Django 6.0.4 on 2026-04-29 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_visit_diagnosis_visit_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.visit'),
        ),
    ]
