# Generated by Django 6.0.4 on 2026-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
