# Generated by Django 6.0.4 on 2026-05-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_patientuploadeddocument'),
        ('appointment', '0011_prescriptionitem_notes'),
    ]

    operations = [
    ]
