# Generated by Django 6.0.4 on 2026-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_merge_20260525_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('video', 'Video')], default='in_person', max_length=20),
        ),
    ]
