# Generated by Django 6.0.4 on 2026-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_merge_20260526_1109'),
        ('appointment', '0013_appointment_consultation_type'),
    ]

    operations = [
    ]
