# Generated by Django 6.0.4 on 2026-05-26 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_familymember_options_alter_patient_options_and_more'),
        ('appointment', '0014_merge_20260526_1516'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(help_text='e.g., Diabetes, Hypertension', max_length=200)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 code if available', max_length=20, null=True)),
                ('diagnosis_date', models.DateField(help_text='When was this condition diagnosed?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('chronic', 'Chronic'), ('in_remission', 'In Remission')], default='active', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='accounts.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical Conditions',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg twice daily', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once daily'), ('twice_daily', 'Twice daily'), ('thrice_daily', 'Thrice daily'), ('four_times_daily', 'Four times daily'), ('as_needed', 'As needed'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=100)),
                ('indication', models.CharField(help_text='Why was this medicine prescribed? e.g., High BP', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if still active', null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration of medication in days', null=True)),
                ('prescribing_doctor', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('effectiveness', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('moderate', 'Moderate'), ('poor', 'Poor'), ('no_effect', 'No Effect')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_history', to='accounts.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medication History',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(help_text='e.g., Appendectomy', max_length=200)),
                ('surgery_date', models.DateField()),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surgeon_name', models.CharField(blank=True, max_length=200, null=True)),
                ('indication', models.TextField(blank=True, help_text='Why was the surgery needed?', null=True)),
                ('complications', models.TextField(blank=True, help_text='Any complications during/after surgery?', null=True)),
                ('recovery_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, help_text='Surgery reports, discharge summary, etc.', related_name='surgery_records', to='appointment.patientuploadeddocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='accounts.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Surgeries',
                'ordering': ['-surgery_date'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(help_text='e.g., Peanuts, Penicillin', max_length=200)),
                ('allergen_type', models.CharField(choices=[('food', 'Food'), ('medication', 'Medication'), ('environmental', 'Environmental'), ('latex', 'Latex'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], max_length=20)),
                ('reaction', models.CharField(choices=[('rash', 'Rash'), ('itching', 'Itching'), ('swelling', 'Swelling'), ('breathing_difficulty', 'Breathing Difficulty'), ('anaphylaxis', 'Anaphylaxis'), ('other', 'Other')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='accounts.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-recorded_date'],
                'unique_together': {('patient', 'allergen', 'allergen_type')},
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(help_text='e.g., COVID-19, DPT, Polio', max_length=200)),
                ('vaccine_type', models.CharField(blank=True, help_text='e.g., mRNA, Inactivated, Live Attenuated', max_length=100, null=True)),
                ('dose_number', models.PositiveIntegerField(default=1, help_text='Which dose is this?')),
                ('vaccination_date', models.DateField()),
                ('next_dose_date', models.DateField(blank=True, help_text='When is next dose due?', null=True)),
                ('administered_by', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, help_text='Hospital/Clinic name', max_length=200, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False, help_text='Is vaccination series complete?')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='vaccination_certificates/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='accounts.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vaccination_date'],
                'unique_together': {('patient', 'vaccine_name', 'dose_number', 'vaccination_date')},
            },
        ),
    ]
