# Generated by Django 6.0.4 on 2026-05-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_medicalcondition_medicationhistory_surgery_allergy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccination',
        ),
    ]
