# Generated by Django 6.0.4 on 2026-05-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_delete_vaccination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcondition',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalcondition',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='medicationhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicationhistory',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='MedicalCondition',
        ),
        migrations.DeleteModel(
            name='MedicationHistory',
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
    ]
