# Generated by Django 6.0.4 on 2026-05-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_merge_20260526_1519'),
        ('appointment', '0017_remove_medicalcondition_patient_and_more'),
    ]

    operations = [
    ]
