# Generated by Django 6.0.4 on 2026-05-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_merge_20260527_1111'),
        ('appointment', '0018_merge_20260527_1118'),
    ]

    operations = [
    ]
