# Generated by Django 6.0.4 on 2026-05-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_merge_20260527_1328'),
        ('appointment', '0019_merge_20260527_1329'),
    ]

    operations = [
    ]
