# Generated by Django 6.0.4 on 2026-05-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_merge_20260527_1443'),
        ('appointment', '0020_merge_20260527_1444'),
    ]

    operations = [
    ]
