# Generated by Django 6.0.4 on 2026-04-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_bld_grop_patient_dob_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-avatar.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
