# Generated by Django 6.0.4 on 2026-05-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='familymember',
            table='accounts_familymember',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='accounts_patient',
        ),
    ]
