# Generated by Django 6.0.4 on 2026-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='Meidicare Clinic', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sepcialization', models.CharField(blank=True, max_length=200, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('slot_duration', models.IntegerField(choices=[(10, '10 Minutes'), (15, '15 Minutes'), (20, '20 Minutes'), (30, '30 Minutes'), (45, '45 Minutes'), (60, '1 Hour')], default=30)),
                ('lunch_start', models.TimeField(default='13:00')),
                ('lunch_end', models.TimeField(default='14:00')),
                ('working_days', models.CharField(default='mon,tue,wed,thu,fri,sat', max_length=50)),
                ('default_gst', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('default_consultion_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bill_prefix', models.CharField(default='BILL', max_length=10)),
                ('bill_footer_note', models.CharField(blank=True, default='Thank You For Visiting Our Clinic', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic & Doctor Information',
                'verbose_name_plural': 'Clinic & Doctor Information',
            },
        ),
    ]
