# Generated by Django 6.0.4 on 2026-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicsettings',
            options={'verbose_name': 'Clinic Settings', 'verbose_name_plural': 'Clinic Settings'},
        ),
        migrations.RenameField(
            model_name='clinicsettings',
            old_name='default_consultion_fee',
            new_name='default_consultation_fee',
        ),
        migrations.RenameField(
            model_name='clinicsettings',
            old_name='qualifications',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='clinicsettings',
            old_name='sepcialization',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='clinicsettings',
            name='created_at',
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='bill_footer_note',
            field=models.CharField(blank=True, default='Thank you for visiting our clinic.', max_length=300),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default='MediCare Clinic', max_length=200),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
