# Generated by Django 6.0.4 on 2026-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_clinicsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='phone_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='video_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
