# Generated by Django 6.0.4 on 2026-05-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinevariant',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='medicinevariant',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinevariant',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinevariant',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='medicinevariant',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('ml', 'ML'), ('gm', 'Gram')], default='piece', max_length=10),
        ),
        migrations.AddField(
            model_name='medicinevariant',
            name='unit_per_strip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
