# Generated by Django 6.0.4 on 2026-05-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_purchase_vendor_purchaseitem_purchase_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('received', 'Received')], default='ordered', max_length=20, null=True),
        ),
    ]
