# Generated by Django 6.0.4 on 2026-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innermember',
            name='role',
            field=models.CharField(choices=[('doctor', 'doctor'), ('biller', 'biller')], max_length=20),
        ),
    ]
