# Generated by Django 6.0.4 on 2026-05-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
