# Generated by Django 6.0.4 on 2026-05-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_delete_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='innermember',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
