# Generated by Django 6.0.4 on 2026-05-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctorleave'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorleave',
            unique_together={('doctor', 'date')},
        ),
        migrations.AlterField(
            model_name='doctorleave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='created_at',
        ),
    ]
