# Generated by Django 6.0.4 on 2026-06-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_doctorleave_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
