# Generated by Django 6.0.4 on 2026-06-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_delete_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='innermember',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Clinic ka owner/main doctor — sirf inhe hi Clinic Settings dikhegi'),
        ),
    ]
