# Generated by Django 6.0.4 on 2026-06-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_assign_owner_for_existing_clinics'),
    ]

    operations = [
        migrations.AddField(
            model_name='innermember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
